import type { Metadata } from "next";
import { Download, ExternalLink, GitPullRequest } from "lucide-react";
import { Reveal } from "@/components/reveal";

export const metadata: Metadata = { title: "Changelog", description: "The Devcanon release timeline and version downloads." };
const releases=[
  {version:"2.1.0",date:"In review",status:"Next",items:["Configurable presets and preset-aware initialization","Interactive standard configuration and local Studio","Expanded theme, motion, responsive, and component standards"],reviewUrl:"https://github.com/KaReeeeeeeeEM/devcanon/pull/1"},
  {version:"2.0.0",date:"Awaiting release",status:"Unpublished",items:["Protected contribution workflow and CODEOWNERS","Source-available project safeguards","Documentation-page design standards"]},
  {version:"1.1.1",date:"August 6, 2026",status:"Latest",items:["Safe refusal at filesystem root","Friendly filesystem error guidance","/install alias and /cd shortcut"]},
  {version:"1.1.0",date:"August 6, 2026",status:"Stable",items:["Interactive terminal with slash shortcuts","Global CLI workflow","Branded documentation and changelog foundation"]},
  {version:"1.0.0",date:"August 6, 2026",status:"Initial",items:["43 production engineering documents","Safe installation for existing repositories","Init, update, check, dry-run, and conflict protection"]},
];
const releaseUrl=(version:string)=>`https://github.com/KaReeeeeeeeEM/devcanon/releases/tag/v${version}`;

export default function Changelog(){return <main><section className="page-hero"><Reveal><p className="section-kicker">Release timeline</p><h1 className="section-title mt-5">Every version, with context and a download.</h1><p className="section-copy mt-5 max-w-2xl">Published packages live on npm and every released version is mirrored on GitHub with its notes and downloadable artifact. Upcoming versions remain clearly marked until publication.</p></Reveal></section><section className="mx-auto max-w-4xl px-5 pb-28 lg:px-8"><div className="relative ml-2 border-l border-border pl-8 sm:pl-12">{releases.map((release,index)=><Reveal key={release.version} delay={index*.05}><article className="relative pb-16 last:pb-0"><span className="absolute -left-[2.39rem] top-2 size-3 rounded-full border-2 border-background bg-cyan-500 sm:-left-[3.39rem]"/><div className="flex flex-wrap items-center gap-3"><h2 className="font-mono text-2xl font-semibold text-foreground">v{release.version}</h2><span className="rounded-full border border-border px-2.5 py-1 font-mono text-[10px] uppercase tracking-wider text-cyan-700 dark:text-cyan-300">{release.status}</span></div><p className="mt-2 text-sm text-muted-foreground">{release.date}</p><ul className="mt-5 space-y-2 text-muted-foreground">{release.items.map(item=><li key={item}>— {item}</li>)}</ul><div className="mt-6 flex flex-wrap gap-3 text-sm">{release.reviewUrl?<a className="button-secondary min-h-10!" href={release.reviewUrl} target="_blank" rel="noreferrer"><GitPullRequest className="size-4"/>Review PR #1</a>:release.status==="Unpublished"?<span className="inline-flex min-h-10 items-center rounded-xl border border-border px-4 text-muted-foreground">Download available after publication</span>:<><a className="button-secondary min-h-10!" href={releaseUrl(release.version)} target="_blank" rel="noreferrer"><Download className="size-4"/>Download from GitHub</a><a className="button-secondary min-h-10!" href={`https://www.npmjs.com/package/devcanon/v/${release.version}`} target="_blank" rel="noreferrer">View on npm <ExternalLink className="size-3"/></a></>}</div></article></Reveal>)}</div></section></main>}
