"use client";

import {
  SiAngular, SiDart, SiDrizzle, SiExpo, SiFirebase, SiFlutter, SiJavascript, SiKotlin,
  SiMongodb, SiMysql, SiNextdotjs, SiPostgresql, SiPrisma, SiPython, SiReact, SiSqlite,
  SiSupabase, SiSvelte, SiSwift, SiTypescript, SiVuedotjs,
} from "@icons-pack/react-simple-icons";
import { ArrowLeft, ArrowRight, Bot, Check, Code2, Copy, Download, Globe2, Laptop, Palette, Server, Settings2, Smartphone, Sparkles, WandSparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Reveal } from "@/components/reveal";

type Product={name:string;description:string;kind:string;stackMode:"choose"|"skip";frontend:string;backend:string;database:string;dataTool:string;mobile:string;language:string;extras:string[];hasDesignReferences:boolean};
const initialProduct:Product={name:"",description:"",kind:"web",stackMode:"skip",frontend:"not-specified",backend:"not-specified",database:"not-specified",dataTool:"none",mobile:"not-specified",language:"not-specified",extras:[],hasDesignReferences:false};
const kinds=[{value:"web",label:"Website",hint:"A site or web app",icon:Globe2},{value:"mobile",label:"Mobile app",hint:"An iPhone or Android app",icon:Smartphone},{value:"api",label:"API",hint:"A backend for other apps",icon:Server},{value:"desktop",label:"Desktop app",hint:"An app for computers",icon:Laptop},{value:"general",label:"Something else",hint:"Tell the AI in your own words",icon:Sparkles}];
const lists={
  frontend:[{v:"not-specified",l:"Let the AI choose"},{v:"nextjs",l:"Next.js",i:SiNextdotjs},{v:"react",l:"React",i:SiReact},{v:"vue",l:"Vue",i:SiVuedotjs},{v:"sveltekit",l:"SvelteKit",i:SiSvelte},{v:"angular",l:"Angular",i:SiAngular},{v:"html-css-js",l:"HTML, CSS & JavaScript",i:SiJavascript},{v:"other",l:"Something else"}],
  backend:[{v:"not-specified",l:"Let the AI choose"},{v:"nextjs",l:"Next.js",i:SiNextdotjs},{v:"node-express",l:"Node.js / Express",i:SiJavascript},{v:"python-fastapi",l:"Python / FastAPI",i:SiPython},{v:"python-django",l:"Python / Django",i:SiPython},{v:"other",l:"Something else"}],
  mobile:[{v:"not-specified",l:"Let the AI choose"},{v:"react-native-expo",l:"React Native / Expo",i:SiExpo},{v:"flutter-dart",l:"Flutter / Dart",i:SiFlutter},{v:"swift-swiftui",l:"Swift / SwiftUI",i:SiSwift},{v:"kotlin-compose",l:"Kotlin / Compose",i:SiKotlin},{v:"other",l:"Something else"}],
  language:[{v:"not-specified",l:"Let the AI choose"},{v:"typescript",l:"TypeScript",i:SiTypescript},{v:"javascript",l:"JavaScript",i:SiJavascript},{v:"python",l:"Python",i:SiPython},{v:"dart",l:"Dart",i:SiDart},{v:"swift",l:"Swift",i:SiSwift},{v:"kotlin",l:"Kotlin",i:SiKotlin},{v:"other",l:"Something else"}],
  database:[{v:"not-specified",l:"Let the AI choose"},{v:"postgresql",l:"PostgreSQL",i:SiPostgresql},{v:"mysql",l:"MySQL",i:SiMysql},{v:"sqlite",l:"SQLite",i:SiSqlite},{v:"mongodb",l:"MongoDB",i:SiMongodb},{v:"supabase",l:"Supabase",i:SiSupabase},{v:"firebase",l:"Firebase",i:SiFirebase},{v:"none",l:"No database"}],
  dataTool:[{v:"drizzle",l:"Drizzle",i:SiDrizzle},{v:"prisma",l:"Prisma",i:SiPrisma},{v:"none",l:"No extra data tool"}],
} as const;
const labels:Record<string,string>={"not-specified":"Let the AI choose",nextjs:"Next.js",react:"React",vue:"Vue",sveltekit:"SvelteKit",angular:"Angular","html-css-js":"HTML, CSS & JavaScript","node-express":"Node.js / Express","python-fastapi":"Python / FastAPI","python-django":"Python / Django","react-native-expo":"React Native / Expo","flutter-dart":"Flutter / Dart","swift-swiftui":"Swift / SwiftUI","kotlin-compose":"Kotlin / Compose",typescript:"TypeScript",javascript:"JavaScript",python:"Python",dart:"Dart",swift:"Swift",kotlin:"Kotlin",postgresql:"PostgreSQL",mysql:"MySQL",sqlite:"SQLite",mongodb:"MongoDB",supabase:"Supabase",firebase:"Firebase",drizzle:"Drizzle",prisma:"Prisma",none:"None",other:"Something else"};
function codeFor(value:unknown,prefix:string){const bytes=new TextEncoder().encode(JSON.stringify(value));let raw="";bytes.forEach(byte=>raw+=String.fromCharCode(byte));return `${prefix}${btoa(raw).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}`}
function productPrompt(product:Product){const picked=product.stackMode==="skip"?"Choose a sensible, simple stack and explain the choice before building.":[`Frontend: ${labels[product.frontend]}`,`Backend: ${labels[product.backend]}`,`Mobile: ${labels[product.mobile]}`,`Language: ${labels[product.language]}`,`Database: ${labels[product.database]}`,`Data tool: ${labels[product.dataTool]}`].filter(line=>!line.endsWith("Let the AI choose")).join("\n");return `Build ${product.name||"this product"} from start to finish.\n\nWhat it is\n${product.description||"Ask me a few short questions to understand the product."}\n\nProduct type\n${kinds.find(item=>item.value===product.kind)?.label||"Other"}\n\nStack\n${picked}\n\n${product.hasDesignReferences?"I have attached design examples. Use them for visual direction, but adapt them to this product and keep the result accessible.":"Create a clear, polished design that fits the product."}\n\nBefore coding, inspect the repository and make a short plan. Reuse its conventions. Build the full working product, including loading, empty, error and success states. Keep security, accessibility, responsive design, data integrity and privacy in every decision. Add useful tests, run all relevant checks, fix failures you caused and finish with a short summary of what works and any honest limitations. Do not leave mock actions or pretend integrations.`}
function ChoiceGrid({items,value,onChange}:{items:readonly {v:string;l:string;i?:React.ComponentType<{className?:string}>}[];value:string;onChange:(v:string)=>void}){return <div className="grid gap-2 sm:grid-cols-2">{items.map(item=>{const Icon=item.i;return <button type="button" key={item.v} onClick={()=>onChange(item.v)} className={`stack-choice ${value===item.v?"stack-choice-active":""}`} aria-pressed={value===item.v}>{Icon?<Icon className="size-5"/>:<Code2 className="size-5"/>}<span>{item.l}</span>{value===item.v&&<Check className="ml-auto size-4"/>}</button>})}</div>}
function Field({title,hint,children}:{title:string;hint?:string;children:React.ReactNode}){return <div><h3 className="text-sm font-semibold">{title}</h3>{hint&&<p className="mb-3 mt-1 text-xs leading-5 text-muted-foreground">{hint}</p>}{children}</div>}

export default function StudioPage(){
  const[product,setProduct]=useState(initialProduct);const[step,setStep]=useState(0);const[copied,setCopied]=useState("");
  const code=useMemo(()=>codeFor(product,"dcp1_"),[product]);const prompt=useMemo(()=>productPrompt(product),[product]);const command=`npx devcanon init --product ${code}`;
  const set=<K extends keyof Product>(key:K,value:Product[K])=>setProduct(current=>({...current,[key]:value}));
  async function copy(value:string,label:string){await navigator.clipboard.writeText(value);setCopied(label);setTimeout(()=>setCopied(""),1500)}
  function download(){const blob=new Blob([JSON.stringify({version:1,code,product,prompt},null,2)],{type:"application/json"});const anchor=document.createElement("a");anchor.href=URL.createObjectURL(blob);anchor.download="devcanon-product.json";anchor.click();URL.revokeObjectURL(anchor.href)}
  const steps=["Your idea","Choose tools","Project type","Your stack","Ready"];
  return <main className="min-w-0 overflow-hidden">
    <section className="page-hero pb-10"><Reveal><div className="eyebrow"><WandSparkles className="size-3.5"/>Product setup</div><h1 className="section-title mt-6 max-w-4xl">Tell Devcanon what you want to make.</h1><p className="section-copy mt-5 max-w-2xl">A few small choices become one clear instruction for your AI. You can skip every technical question.</p></Reveal></section>
    <section className="studio-shell">
      <div className="min-w-0">
        <nav className="setup-steps" aria-label="Setup progress">{steps.map((label,index)=><button type="button" key={label} onClick={()=>index<=step&&setStep(index)} className={index===step?"setup-step-active":index<step?"setup-step-done":""} disabled={index>step}><span>{index<step?<Check/>:index+1}</span><small>{label}</small></button>)}</nav>
        <Card className="mt-5"><CardContent className="space-y-7 p-5 sm:p-7">
          {step===0&&<><div><h2 className="text-2xl font-semibold">What are you making?</h2><p className="mt-2 text-sm text-muted-foreground">No technical words needed. Just explain your idea.</p></div><Field title="Product name"><input className="setup-input" value={product.name} onChange={event=>set("name",event.target.value)} placeholder="Example: My school planner" autoFocus/></Field><Field title="What should it do?" hint="This helps the AI understand who it is for, what problem it solves, and which features matter most."><textarea className="setup-input min-h-32 resize-y" value={product.description} onChange={event=>set("description",event.target.value)} placeholder="Example: Help students see homework, plan study time, and remember due dates." maxLength={4000}/></Field></>}
          {step===1&&<><div><h2 className="text-2xl font-semibold">Do you want to choose the tools?</h2><p className="mt-2 text-sm text-muted-foreground">Both choices work. You can let the AI pick a simple stack.</p></div><button type="button" className={`setup-big-choice ${product.stackMode==="skip"?"stack-choice-active":""}`} onClick={()=>set("stackMode","skip")}><Bot/><span><strong>Let the AI choose</strong><small>Best if you do not know or do not care.</small></span><Check/></button><button type="button" className={`setup-big-choice ${product.stackMode==="choose"?"stack-choice-active":""}`} onClick={()=>set("stackMode","choose")}><Settings2/><span><strong>I want to choose</strong><small>Pick the tools you already like.</small></span><Check/></button></>}
          {step===2&&<><div><h2 className="text-2xl font-semibold">What kind of product is it?</h2><p className="mt-2 text-sm text-muted-foreground">This decides which simple questions come next.</p></div><div className="grid gap-3 sm:grid-cols-2">{kinds.map(item=>{const Icon=item.icon;return <button type="button" key={item.value} onClick={()=>set("kind",item.value)} className={`setup-kind ${product.kind===item.value?"stack-choice-active":""}`}><Icon/><span><strong>{item.label}</strong><small>{item.hint}</small></span>{product.kind===item.value&&<Check/>}</button>})}</div></>}
          {step===3&&<><div><h2 className="text-2xl font-semibold">{product.stackMode==="skip"?"The AI will choose for you":"Choose your stack"}</h2><p className="mt-2 text-sm text-muted-foreground">{product.stackMode==="skip"?"You can go straight to the final prompt. Change your mind here if you want.":"Pick only what you know. Devcanon fills in the rest."}</p></div>{product.stackMode==="choose"&&<div className="space-y-8">{product.kind==="web"&&<><Field title="Frontend" hint="The part people see and click."><ChoiceGrid items={lists.frontend} value={product.frontend} onChange={value=>set("frontend",value)}/></Field><Field title="Backend" hint="The part that handles data and business rules."><ChoiceGrid items={lists.backend} value={product.backend} onChange={value=>set("backend",value)}/></Field></>}{product.kind==="mobile"&&<Field title="Mobile framework"><ChoiceGrid items={lists.mobile} value={product.mobile} onChange={value=>set("mobile",value)}/></Field>}{["api","desktop","general"].includes(product.kind)&&<Field title="Main language"><ChoiceGrid items={lists.language} value={product.language} onChange={value=>set("language",value)}/></Field>}<Field title="Database" hint="Where the product remembers information."><ChoiceGrid items={lists.database} value={product.database} onChange={value=>set("database",value)}/></Field>{product.database!=="none"&&<Field title="Data tool" hint="Optional. It helps your code talk to the database."><ChoiceGrid items={lists.dataTool} value={product.dataTool} onChange={value=>set("dataTool",value)}/></Field>}</div>}<label className="setup-check"><input type="checkbox" checked={product.hasDesignReferences} onChange={event=>set("hasDesignReferences",event.target.checked)}/><Palette/><span><strong>I have design examples</strong><small>The final prompt will remind you to attach them.</small></span></label></>}
          {step===4&&<><div><h2 className="text-2xl font-semibold">Your build prompt is ready</h2><p className="mt-2 text-sm text-muted-foreground">Copy it into your AI coding tool. If you chose design examples, attach those files too.</p></div><div className="rounded-xl border border-border bg-muted/30 p-4"><pre className="max-h-96 overflow-auto whitespace-pre-wrap font-sans text-sm leading-6">{prompt}</pre></div><div className="grid gap-3 sm:grid-cols-2"><Button onClick={()=>copy(prompt,"prompt")}>{copied==="prompt"?<Check/>:<Copy/>}{copied==="prompt"?"Copied":"Copy build prompt"}</Button><Button variant="outline" onClick={download}><Download/>Download everything</Button></div></>}
          <div className="flex justify-between border-t border-border pt-5"><Button variant="outline" onClick={()=>setStep(value=>Math.max(0,value-1))} disabled={step===0}><ArrowLeft/>Back</Button>{step<4&&<Button onClick={()=>setStep(value=>Math.min(4,value+1))}>{step===3?"Make my prompt":"Next"}<ArrowRight/></Button>}</div>
        </CardContent></Card>
      </div>
      <aside className="preset-panel">
        <div className="flex items-center gap-3"><div className="preset-orb"><Sparkles/></div><div><p className="section-kicker">Live summary</p><h2 className="mt-1 text-xl font-semibold">{product.name||"Your product"}</h2></div></div>
        <div className="mt-6 space-y-2 text-sm"><div className="preset-chip"><span>Product</span><strong>{kinds.find(item=>item.value===product.kind)?.label}</strong></div><div className="preset-chip"><span>Tools</span><strong>{product.stackMode==="skip"?"AI chooses":"You choose"}</strong></div><div className="preset-chip"><span>Design examples</span><strong>{product.hasDesignReferences?"Yes":"No"}</strong></div></div>
        <p className="output-label mt-6">Install command</p><div className="output-code command-output">$ {command}</div><Button className="mt-3 w-full" onClick={()=>copy(command,"command")}>{copied==="command"?<Check/>:<Copy/>}{copied==="command"?"Copied":"Copy install command"}</Button>
        <p className="mt-4 text-xs leading-5 text-muted-foreground">The command installs Devcanon and saves this setup as readable files inside your project. Nothing is sent to an account.</p>
        <details className="mt-6 border-t border-border pt-5"><summary className="cursor-pointer text-sm font-semibold">Advanced engineering settings</summary><p className="mt-3 text-xs leading-5 text-muted-foreground">The Devcanon handbook already includes secure, accessible and testable defaults. Detailed presets remain available through the CLI and local Studio.</p></details>
      </aside>
    </section>
  </main>;
}
