"use client";
import { Check, Copy, Download, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";

const options={projectType:["web","api","mobile","library","fullstack"],strictness:["balanced","strict"],design:["product","editorial","marketing","minimal"],density:["comfortable","compact"],accent:["cyan","blue","violet","emerald","amber","rose"],testing:["standard","high"],security:["standard","high"],docs:["three-column","article","api-reference"]} as const;
type Preset=Record<keyof typeof options,string>;
const initial:Preset={projectType:"web",strictness:"balanced",design:"product",density:"comfortable",accent:"cyan",testing:"standard",security:"high",docs:"three-column"};
function codeFor(preset:Preset){const bytes=new TextEncoder().encode(JSON.stringify(preset));let value="";bytes.forEach(byte=>value+=String.fromCharCode(byte));return `dc1_${btoa(value).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}`;}
export default function StudioPage(){const[preset,setPreset]=useState(initial);const[copied,setCopied]=useState("");const code=useMemo(()=>codeFor(preset),[preset]);const command=`npx devcanon init --preset ${code}`;async function copy(value:string,label:string){await navigator.clipboard.writeText(value);setCopied(label);setTimeout(()=>setCopied(""),1500)}function download(){const blob=new Blob([JSON.stringify({version:1,code,preset},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="devcanon-preset.json";a.click();URL.revokeObjectURL(a.href)}return <main><section className="page-hero"><div className="eyebrow"><SlidersHorizontal className="size-3.5"/>Preset builder</div><h1 className="section-title mt-6 max-w-4xl">Make the standards yours. Keep the safeguards.</h1><p className="section-copy mt-5 max-w-2xl">Choose project preferences and generate a private, portable preset code. No account, upload, or server storage required.</p></section><section className="mx-auto grid max-w-7xl gap-8 px-5 pb-24 lg:grid-cols-[1fr_.9fr] lg:px-8"><div className="grid gap-5 sm:grid-cols-2">{Object.entries(options).map(([key,values])=><label className="feature-card" key={key}><span className="font-mono text-xs uppercase tracking-wider text-cyan-400">{key.replace(/([A-Z])/g," $1")}</span><select className="mt-5 w-full rounded-lg border border-white/10 bg-[#07101b] px-3 py-3 text-white" value={preset[key as keyof Preset]} onChange={event=>setPreset(current=>({...current,[key]:event.target.value}))}>{values.map(value=><option key={value}>{value}</option>)}</select></label>)}</div><aside className="self-start rounded-2xl border border-white/10 bg-[#060b13] p-6 lg:sticky lg:top-24"><p className="section-kicker">Your preset</p><h2 className="mt-3 text-2xl font-semibold text-white">Ready to install</h2><p className="mt-3 leading-7 text-slate-400">The code contains only these preferences. Mandatory security and accessibility rules cannot be disabled.</p><div className="mt-6 break-all rounded-xl border border-white/8 bg-white/[.025] p-4 font-mono text-xs leading-6 text-cyan-300">{code}</div><button className="button-secondary mt-4 w-full" onClick={()=>copy(code,"code")}>{copied==="code"?<Check className="size-4"/>:<Copy className="size-4"/>} Copy preset code</button><div className="mt-6 rounded-xl border border-cyan-300/15 bg-cyan-400/[.04] p-4 font-mono text-xs leading-6 text-slate-300">$ {command}</div><button className="command-button mt-4 w-full" onClick={()=>copy(command,"command")}>{copied==="command"?<Check className="size-4"/>:<Copy className="size-4"/>} Copy install command</button><button className="button-secondary mt-3 w-full" onClick={download}><Download className="size-4"/> Download JSON</button></aside></section></main>}
