import type { Metadata } from "next";
import { ArrowLeft, ArrowUpRight, Download, HardDriveDownload } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { desktopPlatformKeys, desktopPlatforms, type DesktopPlatform } from "@/lib/desktop-platforms";

type ReleaseAsset={id:number;name:string;browser_download_url:string;size:number;download_count:number};
type Release={id:number;tag_name:string;name:string|null;published_at:string;html_url:string;body:string|null;assets:ReleaseAsset[]};

export const revalidate=300;
export function generateStaticParams(){return desktopPlatformKeys.map(platform=>({platform}))}
export async function generateMetadata({params}:{params:Promise<{platform:string}>}):Promise<Metadata>{const{platform}=await params;if(!(platform in desktopPlatforms))return{};const item=desktopPlatforms[platform as DesktopPlatform];return{title:`Devcanon Studio for ${item.name}`,description:`Download Devcanon Studio installers and previous releases for ${item.name}.`}}
function size(bytes:number){if(bytes<1024*1024)return`${Math.ceil(bytes/1024)} KB`;return`${(bytes/1024/1024).toFixed(1)} MB`}
async function releasesFor(platform:DesktopPlatform){try{const response=await fetch("https://api.github.com/repos/KaReeeeeeeeEM/devcanon-website/releases?per_page=30",{headers:{Accept:"application/vnd.github+json"},next:{revalidate:300}});if(!response.ok)return[];const releases=await response.json() as Release[];return releases.map(release=>({...release,assets:release.assets.filter(asset=>desktopPlatforms[platform].pattern.test(asset.name))})).filter(release=>release.assets.length)}catch{return[]}}

export default async function PlatformDownloads({params}:{params:Promise<{platform:string}>}){const value=(await params).platform;if(!(value in desktopPlatforms))notFound();const platform=value as DesktopPlatform,item=desktopPlatforms[platform],Icon=item.icon,releases=await releasesFor(platform);return <main className="platform-download-page">
  <section className="platform-download-hero"><Link className="back-link" href="/download"><ArrowLeft/> All download options</Link><div className="platform-title-icon"><Icon/></div><p className="section-kicker">Devcanon Studio</p><h1>Download for {item.name}</h1><p>{item.description} Choose the newest installer or return to an earlier release whenever your environment requires it.</p><div className="format-list">{item.formats.map(format=><span key={format}>{format}</span>)}</div></section>
  <section className="release-browser"><div className="release-browser-heading"><div><p className="section-kicker">Release archive</p><h2>Available {item.name} builds</h2></div><a href="https://github.com/KaReeeeeeeeEM/devcanon-website/releases" target="_blank" rel="noreferrer">View on GitHub <ArrowUpRight/></a></div>
    {releases.length?<div className="release-table-wrap"><table className="release-table"><caption className="sr-only">Devcanon Studio releases for {item.name}</caption><thead><tr><th scope="col">Version</th><th scope="col">Installer</th><th scope="col">Published</th><th scope="col">Size</th><th scope="col">Downloads</th><th scope="col"><span className="sr-only">Download</span></th></tr></thead><tbody>{releases.flatMap((release,index)=>release.assets.map(asset=><tr key={asset.id}><td><a className="release-version-link" href={release.html_url} target="_blank" rel="noreferrer">{release.name||release.tag_name}<ArrowUpRight/></a>{index===0&&<span className="latest-badge">Latest</span>}</td><td><a className="installer-link" href={asset.browser_download_url}><HardDriveDownload/><span>{asset.name}</span></a></td><td><time dateTime={release.published_at}>{new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(new Date(release.published_at))}</time></td><td>{size(asset.size)}</td><td>{asset.download_count.toLocaleString()}</td><td><a className="table-download-link" href={asset.browser_download_url} aria-label={`Download ${asset.name}`}><Download/> Download</a></td></tr>))}</tbody></table></div>:<div className="empty-releases"><HardDriveDownload/><h3>The first {item.name} build is being prepared.</h3><p>Published installers will appear here automatically from GitHub Releases.</p><a className="button-primary" href="https://github.com/KaReeeeeeeeEM/devcanon-website/releases" target="_blank" rel="noreferrer">Watch GitHub Releases <ArrowUpRight/></a></div>}
  </section>
</main>}
