import { ArrowRight, Blocks, BookOpen, Check, GitPullRequest, Layers3, LockKeyhole, RefreshCw, ShieldCheck, Sparkles, Terminal, WandSparkles, Workflow } from "lucide-react";
import Link from "next/link";
import { AnimatedTerminal } from "@/components/animated-terminal";
import { CopyCommand } from "@/components/copy-command";
import { Reveal } from "@/components/reveal";
import { RippleBackground } from "@/components/ripple-background";
import { TechnologyMarquee } from "@/components/technology-marquee";

const standards = ["Architecture", "Product design", "Frontend", "Backend", "API design", "Database", "Security", "Accessibility", "Testing", "Deployment", "Observability", "AI features"];
const steps = [{n:"01",title:"Install",copy:"Add Devcanon to a new or existing repository in one command."},{n:"02",title:"Configure",copy:"Choose a preset in Studio or tailor individual standards locally."},{n:"03",title:"Build",copy:"Every AI agent reads the same durable engineering judgment."}];
const faqs = [{q:"Does Devcanon overwrite my files?",a:"No. Existing instructions and modified standards are preserved unless you explicitly opt into replacement."},{q:"Does it work with existing repositories?",a:"Yes. Existing repositories are the primary workflow; Devcanon adds only what is missing and reports differences."},{q:"Which AI coding tools can use it?",a:"Any tool that reads repository Markdown instructions can use the handbook, including Codex, Claude Code, and IDE agents."},{q:"Are presets stored on a server?",a:"No. Preset codes are portable, deterministic, and generated locally in your browser."}];

export default function Home() { return <main className="overflow-hidden">
  <section className="hero-grid relative border-b border-border/70"><RippleBackground/><div className="relative z-10 mx-auto grid min-h-[760px] max-w-7xl items-center gap-14 px-5 py-24 lg:grid-cols-[1.08fr_.92fr] lg:px-8"><Reveal><div className="eyebrow"><Sparkles className="size-3.5"/> Engineering standards, on command</div><h1 className="hero-title">Give every AI agent your engineering judgment.</h1><p className="hero-copy">Devcanon installs a durable engineering handbook into any repository—so architecture, design, security, testing, and delivery stay consistent without repeating yourself.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><CopyCommand command="npx devcanon init" prominent/><Link href="/studio" className="button-secondary">Build your preset <ArrowRight className="size-4"/></Link></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-sm text-muted-foreground"><span className="benefit"><Check/>Existing repos first</span><span className="benefit"><Check/>Private by default</span><span className="benefit"><Check/>Safe updates</span></div></Reveal><Reveal delay={.15}><AnimatedTerminal/></Reveal></div></section>
  <section className="border-b border-border/70"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-border/70 px-5 sm:grid-cols-4 lg:px-8">{[["43","focused standards"],["10","feature blueprints"],["0","runtime dependencies"],["1","shared source of truth"]].map(([value,label])=><div className="px-4 py-9 text-center" key={label}><strong className="font-mono text-2xl text-foreground sm:text-3xl">{value}</strong><p className="mt-2 text-xs text-muted-foreground sm:text-sm">{label}</p></div>)}</div></section>

  <section className="section-shell"><Reveal className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="section-kicker">One install. Shared judgment.</p><h2 className="section-title mt-4">A real handbook, not another prompt file.</h2><p className="section-copy mt-5">Each concern has one authoritative home. Agents read only what the task requires while precedence rules keep decisions coherent.</p></div><div className="standards-grid">{standards.map((standard,index)=><div key={standard}><span>{String(index+1).padStart(2,"0")}</span>{standard}</div>)}</div></Reveal></section>
  <TechnologyMarquee />

  <section className="border-y border-border/70 bg-muted/25"><div className="section-shell"><Reveal><p className="section-kicker text-center">A workflow that stays out of your way</p><h2 className="section-title mx-auto mt-4 max-w-3xl text-center">From empty folder to aligned engineering team.</h2><div className="mt-14 grid gap-5 md:grid-cols-3">{steps.map(step=><article className="feature-card" key={step.n}><span className="font-mono text-xs text-cyan-500">{step.n}</span><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div></Reveal></div></section>

  <section className="section-shell"><Reveal><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{[[Terminal,"Works everywhere","Run globally, through npx, or pin the version for a whole team."],[ShieldCheck,"Preserves intent","Local changes are reported and never silently replaced."],[GitPullRequest,"Reviewable by design","Version standards beside code and update them through pull requests."],[WandSparkles,"Portable presets","Carry a complete design and engineering profile in one short code."],[RefreshCw,"Safe evolution","Preview handbook updates and understand every local difference."],[LockKeyhole,"Security stays mandatory","Presets can personalize choices but cannot weaken core safeguards."]].map(([Icon,title,copy])=><article className="feature-card" key={String(title)}>{typeof Icon!=="string"&&<Icon/>}<h3>{String(title)}</h3><p>{String(copy)}</p></article>)}</div></Reveal></section>

  <section className="border-y border-border/70 bg-muted/25"><div className="section-shell"><Reveal className="grid items-center gap-12 lg:grid-cols-2"><div><p className="section-kicker">Designed for the full lifecycle</p><h2 className="section-title mt-4">Standards that travel from idea to production.</h2><p className="section-copy mt-5">The same source of truth guides product surfaces, backend contracts, secure delivery, testing, observability, and documentation.</p><Link href="/docs" className="button-secondary mt-8">Explore the handbook <ArrowRight className="size-4"/></Link></div><div className="orbit-card"><div><Blocks/><span>Design</span></div><div><Layers3/><span>Build</span></div><div><Workflow/><span>Ship</span></div><div className="orbit-center">D›</div></div></Reveal></div></section>

  <section className="section-shell"><Reveal><p className="section-kicker text-center">Questions, answered</p><h2 className="section-title mt-4 text-center">Built to be adopted, not babysat.</h2><div className="mx-auto mt-12 max-w-3xl divide-y divide-border rounded-2xl border border-border bg-card">{faqs.map(item=><details className="group p-5 sm:p-6" key={item.q}><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-medium text-card-foreground">{item.q}<span className="text-cyan-500 transition group-open:rotate-45">+</span></summary><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">{item.a}</p></details>)}</div></Reveal></section>

  <section className="relative border-t border-border/70"><RippleBackground/><Reveal className="relative z-10 mx-auto max-w-4xl px-5 py-28 text-center"><BookOpen className="mx-auto size-8 text-cyan-500"/><h2 className="section-title mt-6">Stop re-explaining how good work should look.</h2><p className="section-copy mx-auto mt-5 max-w-2xl">Install Devcanon, open your AI coding tool, and move from idea to implementation with the standards already in the room.</p><div className="mt-9 flex justify-center"><CopyCommand command="npm install --global devcanon" prominent/></div></Reveal></section>
</main>; }
