import type { Metadata } from "next";
import { CopyCommand } from "@/components/copy-command";
import { DocsNav } from "@/components/docs-nav";
export const metadata: Metadata = { title: "Documentation", description: "Install and use devcanon in new or existing repositories." };
export default function DocsPage(){return <main className="docs-shell"><DocsNav/><article className="docs-article"><p className="section-kicker">Documentation / Introduction</p><h1 className="mt-4">Build with standards already in the room.</h1><p className="text-lg! leading-8!">Devcanon gives AI coding agents a structured source of truth for engineering decisions. It installs into existing repositories safely and adapts to local conventions.</p><div className="callout"><strong className="text-white">What it does not do:</strong> devcanon does not replace your framework, execute repository code, upload source, or overwrite modified standards by default.</div>
<h2 id="get-started">Get started</h2><h3>1. Choose your installation</h3><p>Use npx for the fastest first run:</p><div className="mt-4"><CopyCommand command="npx devcanon init" /></div><p>Or install the interactive CLI globally:</p><div className="mt-4"><CopyCommand command="npm install --global devcanon" /></div><h3>2. Run inside your repository</h3><p>Change into the project first. Devcanon refuses to install at the filesystem root.</p><div className="mt-4"><CopyCommand command="cd /path/to/project && devcanon" /></div><h3>3. Give the agent a task</h3><p>The generated root <code>AGENTS.md</code> directs compatible tools to <code>.ai/AGENTS.md</code>. The agent reads relevant standards before changing code.</p>
<h2 id="interactive">Interactive CLI</h2><p>Run <code>devcanon</code> with no arguments to open the command prompt. Slash shortcuts keep repository setup quick and discoverable.</p><div className="terminal-window mt-6"><div className="terminal-bar"><span/><span/><span/><p>interactive session</p></div><pre className="overflow-x-auto p-6 font-mono text-sm leading-8 text-slate-300"><span className="text-cyan-400">devcanon ›</span> /where{"\n"}<span className="text-slate-500">/Users/you/Projects/app</span>{"\n"}<span className="text-cyan-400">devcanon ›</span> /init{"\n"}<span className="text-emerald-400">✓ 43 standards installed</span>{"\n"}<span className="text-cyan-400">devcanon ›</span> /check</pre></div><p>Started in the wrong directory? Use <code>/cd /path/to/project</code>. The alias <code>/install</code> behaves like <code>/init</code>.</p>
<h2 id="commands">Command reference</h2><ul><li><code>init [path]</code> — adds missing standards and preserves local files.</li><li><code>update [path]</code> — compares packaged standards and reports conflicts.</li><li><code>check [path]</code> — validates all 43 documents and required sections.</li><li><code>--dry-run</code> — previews operations without writing.</li><li><code>--force</code> — explicitly replaces differing standards.</li><li><code>--no-root-agents</code> — skips the root discovery file.</li></ul>
<h2 id="updates">Update safely</h2><p>Update the CLI first, then preview handbook changes inside each repository. Treat standards upgrades like code changes.</p><div className="mt-4 space-y-3"><CopyCommand command="npm install --global devcanon@latest"/><br/><CopyCommand command="devcanon update --dry-run"/><br/><CopyCommand command="devcanon update"/></div><div className="callout"><strong className="text-white">Conflict means preserved.</strong> A reported conflict is not a failed install. It means the repository has a local version that devcanon intentionally left untouched.</div>
</article><aside className="toc"><p className="font-mono uppercase tracking-widest">On this page</p><a href="#get-started">Get started</a><a href="#interactive">Interactive CLI</a><a href="#commands">Commands</a><a href="#updates">Safe updates</a></aside></main>}
