const {invoke,Channel}=window.__TAURI__.core;
const $=selector=>document.querySelector(selector);
const elements={sidebar:$("#sidebar"),collapse:$("#collapse"),expand:$("#expand"),choose:$("#choose-project"),emptyOpen:$("#empty-open"),projects:$("#project-list"),projectCount:$("#project-count"),projectScanStatus:$("#project-scan-status"),refreshProjects:$("#refresh-projects"),files:$("#file-list"),count:$("#file-count"),name:$("#file-name"),empty:$("#empty-state"),editor:$("#editor"),save:$("#save"),state:$("#save-state"),standardsUpdate:$("#standards-update"),toast:$("#toast"),projectModal:$("#project-modal"),newProject:$("#new-project"),existingProject:$("#existing-project"),version:$("#version"),appUpdate:$("#app-update"),availableVersion:$("#available-version"),updateStatus:$("#update-status"),updatePage:$("#update-page"),closeUpdate:$("#close-update"),installUpdate:$("#install-update"),updateVersion:$("#update-version"),updateNotes:$("#update-notes"),updateMessage:$("#update-message"),progressPercent:$("#progress-percent"),progressEta:$("#progress-eta"),progressBar:$("#progress-bar"),assetStatus:$("#asset-status"),assetName:$("#asset-name"),assetSize:$("#asset-size"),assetProgress:$("#asset-progress"),welcomeModal:$("#welcome-modal"),welcomeVersion:$("#welcome-version"),welcomeFeatures:$("#welcome-features"),finishWelcome:$("#finish-welcome")};
let project="",current="",dirty=false,toastTimer,pendingUpdate=null,studioVersion="",discoveredProjects=[];
const recentKey="devcanon-recent-projects-v1",welcomeKey="devcanon-pending-welcome-v1";
function notify(message,error=false){clearTimeout(toastTimer);elements.toast.textContent=message;elements.toast.className=`toast visible${error?" error":""}`;toastTimer=setTimeout(()=>elements.toast.className="toast",3600)}
function setDirty(value){dirty=value;elements.state.textContent=current?(value?"Unsaved changes":"All changes saved"):"No file open"}
function basename(path){return path.split(/[\\/]/).filter(Boolean).pop()||path}
function recentProjects(){try{return JSON.parse(localStorage.getItem(recentKey)||"[]")}catch{return[]}}
function rememberProject(path){const projects=[path,...recentProjects().filter(item=>item!==path)].slice(0,8);localStorage.setItem(recentKey,JSON.stringify(projects));renderProjects()}
function allProjects(){return [...new Set([...recentProjects(),...discoveredProjects])]}
function renderProjects(){const projects=allProjects();elements.projectCount.textContent=String(projects.length);elements.projects.replaceChildren(...projects.map(path=>{const button=document.createElement("button");button.className=`project-item${path===project?" active":""}`;button.title=path;const glyph=document.createElement("span");glyph.className="project-glyph";glyph.textContent="◇";const label=document.createElement("span");label.textContent=basename(path);button.append(glyph,label);button.addEventListener("click",()=>loadProject(path));return button}))}
async function discoverProjects(){elements.refreshProjects.disabled=true;elements.refreshProjects.classList.add("scanning");elements.projectScanStatus.textContent="Scanning…";try{discoveredProjects=await invoke("discover_projects");elements.projectScanStatus.textContent=discoveredProjects.length?"Detected":"None found";renderProjects()}catch(error){elements.projectScanStatus.textContent="Scan unavailable";notify(String(error),true)}finally{elements.refreshProjects.disabled=false;elements.refreshProjects.classList.remove("scanning")}}
function openLauncher(){elements.projectModal.hidden=false;elements.newProject.focus()}
function closeLauncher(){elements.projectModal.hidden=true}
function notesList(notes){const lines=(notes||"A faster, safer Devcanon Studio experience.").split("\n").map(line=>line.replace(/^[-*#\s]+/,"").trim()).filter(Boolean).slice(0,6);const list=document.createElement("ul");list.replaceChildren(...lines.map(line=>{const item=document.createElement("li");item.textContent=line;return item}));return list}
async function loadProject(path){if(dirty){notify("Save your current changes before switching projects.",true);return}try{const files=await invoke("list_standards",{project:path});project=path;current="";elements.name.textContent=basename(project);elements.count.textContent=String(files.length);elements.files.replaceChildren(...files.map(relative=>{const button=document.createElement("button");button.className="file-item";button.textContent=relative;button.title=relative;button.addEventListener("click",()=>openFile(relative,button));return button}));elements.standardsUpdate.disabled=false;elements.save.disabled=true;elements.editor.hidden=true;elements.empty.hidden=false;elements.empty.querySelector("h2").textContent=files.length?"Choose a standard from the sidebar.":"No standards found.";elements.empty.querySelector("p:not(.eyebrow)").textContent=`${files.length} standards detected in ${basename(project)}.`;rememberProject(project);setDirty(false);notify(`Opened ${basename(project)}`)}catch(error){notify(String(error),true)}}
async function chooseExisting(){closeLauncher();try{const selected=await invoke("choose_project");if(selected)await loadProject(selected)}catch(error){notify(String(error),true)}}
async function createProject(){closeLauncher();notify("Choose an empty or existing project folder to initialize.");try{const selected=await invoke("initialize_project");if(selected)await loadProject(selected)}catch(error){notify(String(error),true)}}
async function openFile(relative,button){if(dirty){notify("Save your current changes before opening another standard.",true);return}try{current=relative;elements.editor.value=await invoke("read_standard",{project,relative});elements.name.textContent=relative;elements.empty.hidden=true;elements.editor.hidden=false;elements.save.disabled=false;document.querySelectorAll(".file-item").forEach(item=>item.classList.toggle("active",item===button));setDirty(false)}catch(error){notify(String(error),true)}}
async function save(){if(!current)return;try{await invoke("write_standard",{project,relative:current,contents:elements.editor.value});setDirty(false);notify(`${current} saved`)}catch(error){notify(String(error),true)}}
async function updateHandbook(){if(!project)return;try{elements.standardsUpdate.disabled=true;elements.standardsUpdate.textContent="Updating…";const result=await invoke("update_standards",{project});notify(result||"Handbook is up to date");await loadProject(project)}catch(error){notify(String(error),true)}finally{elements.standardsUpdate.disabled=false;elements.standardsUpdate.textContent="Update handbook"}}
function setCollapsed(collapsed){document.body.classList.toggle("sidebar-collapsed",collapsed);localStorage.setItem("devcanon-sidebar-collapsed",String(collapsed))}
function prepareUpdate(info){pendingUpdate=info;elements.availableVersion.textContent=`Version ${info.version}`;elements.appUpdate.hidden=false;elements.updateStatus.textContent="A newer Studio release is ready";elements.updateVersion.textContent=info.version;elements.updateNotes.replaceChildren(notesList(info.notes));elements.assetName.textContent=`Devcanon Studio ${info.version} · signed package`}
async function checkForUpdates(){try{const info=await invoke("check_for_app_update");if(info)prepareUpdate(info)}catch{elements.updateStatus.textContent="Update check unavailable"}}
function openUpdatePage(){if(!pendingUpdate)return;elements.updatePage.hidden=false}
function formatBytes(bytes){if(!bytes)return"0 MB";return`${(bytes/1024/1024).toFixed(1)} MB`}
function etaLabel(seconds){if(!Number.isFinite(seconds)||seconds<=0)return"Calculating time remaining…";if(seconds<60)return`About ${Math.ceil(seconds)} seconds remaining`;return`About ${Math.ceil(seconds/60)} minutes remaining`}
async function installUpdate(){if(!pendingUpdate)return;elements.installUpdate.disabled=true;elements.closeUpdate.hidden=true;elements.updateMessage.textContent="Downloading and verifying the signed update…";localStorage.setItem(welcomeKey,JSON.stringify({version:pendingUpdate.version,notes:pendingUpdate.notes}));let downloaded=0,total=0,startedAt=performance.now();const channel=new Channel();channel.onmessage=message=>{if(message.event==="Started"){total=message.data.contentLength||0;startedAt=performance.now();elements.assetStatus.textContent="↓";elements.assetSize.textContent=total?`${formatBytes(total)} signed update package`:"Signed update package"}else if(message.event==="Progress"){downloaded+=message.data.chunkLength;const elapsed=(performance.now()-startedAt)/1000;const percent=total?Math.min(100,downloaded/total*100):0;const speed=elapsed>0?downloaded/elapsed:0;elements.progressPercent.textContent=total?`${Math.round(percent)}%`:"…";elements.progressBar.style.width=total?`${percent}%`:"18%";elements.progressEta.textContent=total&&speed?etaLabel((total-downloaded)/speed):"Downloading update assets…";elements.assetProgress.textContent=total?`${formatBytes(downloaded)} / ${formatBytes(total)}`:formatBytes(downloaded)}else if(message.event==="Finished"){elements.progressPercent.textContent="100%";elements.progressBar.style.width="100%";elements.progressEta.textContent="Download complete";elements.assetStatus.textContent="✓";elements.updateMessage.textContent="Installing the update. Studio will restart automatically…"}};try{await invoke("install_app_update",{onEvent:channel})}catch(error){localStorage.removeItem(welcomeKey);elements.installUpdate.disabled=false;elements.closeUpdate.hidden=false;elements.updateMessage.textContent="The update could not be installed.";notify(String(error),true)}}
function showWelcomeIfNeeded(){try{const update=JSON.parse(localStorage.getItem(welcomeKey)||"null");if(!update||update.version!==studioVersion)return;localStorage.removeItem(welcomeKey);elements.welcomeVersion.textContent=`v${update.version}`;const lines=(update.notes||"Your desktop standards workflow is now up to date.").split("\n").map(line=>line.replace(/^[-*#\s]+/,"").trim()).filter(Boolean).slice(0,5);elements.welcomeFeatures.replaceChildren(...lines.map(line=>{const row=document.createElement("div");row.className="welcome-feature";const icon=document.createElement("span");icon.textContent="✓";const text=document.createElement("p");text.textContent=line;row.append(icon,text);return row}));elements.welcomeModal.hidden=false}catch{localStorage.removeItem(welcomeKey)}}
async function start(){renderProjects();setCollapsed(localStorage.getItem("devcanon-sidebar-collapsed")==="true");discoverProjects();try{const info=await invoke("studio_info");studioVersion=info.version;elements.version.textContent=`v${studioVersion}`;showWelcomeIfNeeded()}catch{elements.version.textContent="Studio"}checkForUpdates()}
elements.choose.addEventListener("click",openLauncher);elements.emptyOpen.addEventListener("click",openLauncher);elements.refreshProjects.addEventListener("click",discoverProjects);elements.newProject.addEventListener("click",createProject);elements.existingProject.addEventListener("click",chooseExisting);elements.projectModal.addEventListener("click",event=>{if(event.target===elements.projectModal||event.target.closest("[data-close-modal]"))closeLauncher()});elements.save.addEventListener("click",save);elements.standardsUpdate.addEventListener("click",updateHandbook);elements.editor.addEventListener("input",()=>setDirty(true));elements.collapse.addEventListener("click",()=>setCollapsed(true));elements.expand.addEventListener("click",()=>setCollapsed(false));elements.appUpdate.addEventListener("click",openUpdatePage);elements.closeUpdate.addEventListener("click",()=>elements.updatePage.hidden=true);elements.installUpdate.addEventListener("click",installUpdate);elements.finishWelcome.addEventListener("click",()=>elements.welcomeModal.hidden=true);window.addEventListener("keydown",event=>{if(event.key==="Escape"){closeLauncher();if(!elements.closeUpdate.hidden)elements.updatePage.hidden=true}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="o"){event.preventDefault();openLauncher()}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="s"){event.preventDefault();save()}});window.addEventListener("beforeunload",event=>{if(dirty)event.preventDefault()});start();
