const {invoke,Channel}=window.__TAURI__.core;
const $=selector=>document.querySelector(selector);
const elements={sidebar:$("#sidebar"),collapse:$("#collapse"),expand:$("#expand"),choose:$("#choose-project"),emptyOpen:$("#empty-open"),projects:$("#project-list"),projectCount:$("#project-count"),projectScanStatus:$("#project-scan-status"),refreshProjects:$("#refresh-projects"),projectSearch:$("#project-search"),clearProjectSearch:$("#clear-project-search"),files:$("#file-list"),count:$("#file-count"),name:$("#file-name"),empty:$("#empty-state"),editor:$("#editor"),save:$("#save"),state:$("#save-state"),standardsUpdate:$("#standards-update"),openInEditor:$("#open-in-editor"),editorMenu:$("#editor-menu"),toast:$("#toast"),projectModal:$("#project-modal"),newProject:$("#new-project"),existingProject:$("#existing-project"),version:$("#version"),appUpdate:$("#app-update"),availableVersion:$("#available-version"),updateStatus:$("#update-status"),updatePage:$("#update-page"),closeUpdate:$("#close-update"),installUpdate:$("#install-update"),updateVersion:$("#update-version"),updateNotes:$("#update-notes"),updateMessage:$("#update-message"),progressPercent:$("#progress-percent"),progressEta:$("#progress-eta"),progressBar:$("#progress-bar"),assetStatus:$("#asset-status"),assetName:$("#asset-name"),assetSize:$("#asset-size"),assetProgress:$("#asset-progress"),welcomeModal:$("#welcome-modal"),welcomeVersion:$("#welcome-version"),welcomeFeatures:$("#welcome-features"),finishWelcome:$("#finish-welcome")};
let project="",current="",dirty=false,toastTimer,pendingUpdate=null,studioVersion="",discoveredProjects=[],projectQuery="",editors=[];
const recentKey="devcanon-recent-projects-v1",welcomeKey="devcanon-pending-welcome-v1";
function notify(message,error=false){clearTimeout(toastTimer);elements.toast.textContent=message;elements.toast.className=`toast visible${error?" error":""}`;toastTimer=setTimeout(()=>elements.toast.className="toast",3600)}
function setDirty(value){dirty=value;elements.state.textContent=current?(value?"Unsaved changes":"All changes saved"):"No file open"}
function basename(path){return path.split(/[\\/]/).filter(Boolean).pop()||path}
function recentProjects(){try{return JSON.parse(localStorage.getItem(recentKey)||"[]")}catch{return[]}}
function rememberProject(path){const projects=[path,...recentProjects().filter(item=>item!==path)].slice(0,8);localStorage.setItem(recentKey,JSON.stringify(projects));renderProjects()}
function allProjects(){return [...new Set([...recentProjects(),...discoveredProjects])]}
function editorLogo(id){const paths={vscode:"M17.8 1.5 7.4 11 2.8 7.5.8 9.2l4.4 4.8L.8 18.8l2 1.7 4.6-3.5 10.4 9.5 5.4-2.2V3.7L17.8 1.5Zm0 6v9l-6-4.5 6-4.5Z",cursor:"M11.503.131 1.891 5.678a.84.84 0 0 0-.42.726v11.188c0 .3.162.575.42.724l9.609 5.55a1 1 0 0 0 .998 0l9.61-5.55a.84.84 0 0 0 .42-.724V6.404a.84.84 0 0 0-.42-.726L12.497.131a1.01 1.01 0 0 0-.996 0M2.657 6.338h18.55c.263 0 .43.287.297.515L12.23 22.918c-.062.107-.229.064-.229-.06V12.335a.59.59 0 0 0-.295-.51l-9.11-5.257c-.109-.063-.064-.23.061-.23",conductor:"M12 2a10 10 0 1 0 7.1 17.1l-3-3A5.8 5.8 0 1 1 16.1 8l3-3A10 10 0 0 0 12 2Zm0 6.3a3.7 3.7 0 1 0 2.6 6.3L12 12l2.6-2.6A3.7 3.7 0 0 0 12 8.3Z",windsurf:"M23.55 5.067c-1.204-.002-2.181.973-2.181 2.177v4.867c0 .972-.803 1.76-1.76 1.76-.568 0-1.135-.286-1.471-.766l-4.972-7.1c-.412-.59-1.084-.942-1.81-.942-1.133 0-2.153.964-2.153 2.153v4.896c0 .972-.797 1.759-1.76 1.759-.57 0-1.136-.286-1.472-.766L.408 5.16C.282 4.98 0 5.069 0 5.288v4.245c0 .215.066.423.188.599l5.475 7.819c.323.462.8.805 1.351.93 1.377.312 2.645-.748 2.645-2.098V11.89c0-.972.787-1.76 1.76-1.76a1.8 1.8 0 0 1 1.474.766l4.972 7.1c.414.59 1.05.94 1.81.94 1.158 0 2.151-.964 2.151-2.153V11.89c0-.972.788-1.76 1.76-1.76h.194a.22.22 0 0 0 .22-.22V5.287a.22.22 0 0 0-.22-.22Z",zed:"M2.25 1.5a.75.75 0 0 0-.75.75v16.5H0V2.25A2.25 2.25 0 0 1 2.25 0h20.095c1.002 0 1.504 1.212.795 1.92L10.764 14.298h3.486V12.75h1.5v1.922a1.125 1.125 0 0 1-1.125 1.125H9.264l-2.578 2.578h11.689V9h1.5v9.375a1.5 1.5 0 0 1-1.5 1.5H5.185L2.562 22.5H21.75a.75.75 0 0 0 .75-.75V5.25H24v16.5A2.25 2.25 0 0 1 21.75 24H1.655C.653 24 .151 22.788.86 22.08L13.19 9.75H9.75v1.5h-1.5V9.375A1.125 1.125 0 0 1 9.375 8.25h5.314l2.625-2.625H5.625V15h-1.5V5.625a1.5 1.5 0 0 1 1.5-1.5h13.19L21.438 1.5z"};const logo=document.createElement("span");logo.className=`editor-logo editor-logo-${id}`;logo.setAttribute("aria-hidden","true");const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("viewBox","0 0 24 24");const path=document.createElementNS("http://www.w3.org/2000/svg","path");path.setAttribute("d",paths[id]||paths.vscode);svg.append(path);logo.append(svg);return logo}
function closeEditorMenu(){elements.editorMenu.hidden=true;elements.openInEditor.setAttribute("aria-expanded","false")}
function renderEditors(){elements.editorMenu.replaceChildren(...editors.map(editor=>{const button=document.createElement("button");button.type="button";button.setAttribute("role","menuitem");button.disabled=!editor.available;button.dataset.editor=editor.id;button.append(editorLogo(editor.id));const copy=document.createElement("span");const name=document.createElement("strong");name.textContent=editor.name;const status=document.createElement("small");status.textContent=editor.available?"Open this project":"Not installed";copy.append(name,status);button.append(copy);button.addEventListener("click",()=>openProjectInEditor(editor));return button}))}
async function loadEditors(){try{editors=await invoke("list_editors");renderEditors()}catch{editors=[];renderEditors()}}
async function openProjectInEditor(editor){if(!project||!editor.available)return;closeEditorMenu();try{await invoke("open_in_editor",{project,editor:editor.id});notify(`Opened ${basename(project)} in ${editor.name}`)}catch(error){notify(String(error),true)}}
function toggleEditorMenu(){if(!project)return;const opening=elements.editorMenu.hidden;elements.editorMenu.hidden=!opening;elements.openInEditor.setAttribute("aria-expanded",String(opening));if(opening){const first=elements.editorMenu.querySelector("button:not(:disabled)");if(first)first.focus()}}
function moveEditorFocus(event){if(!["ArrowDown","ArrowUp","Home","End"].includes(event.key))return;const items=[...elements.editorMenu.querySelectorAll("button:not(:disabled)")];if(!items.length)return;event.preventDefault();const current=items.indexOf(document.activeElement);const next=event.key==="Home"?0:event.key==="End"?items.length-1:event.key==="ArrowDown"?(current+1)%items.length:(current-1+items.length)%items.length;items[next].focus()}
function renderProjects(){const all=allProjects(),query=projectQuery.trim().toLocaleLowerCase(),projects=query?all.filter(path=>`${basename(path)} ${path}`.toLocaleLowerCase().includes(query)):all;elements.projectCount.textContent=query?`${projects.length}/${all.length}`:String(all.length);elements.clearProjectSearch.hidden=!query;if(!projects.length){const empty=document.createElement("p");empty.className="project-search-empty";empty.textContent=query?`No projects match “${projectQuery.trim()}”.`:"No Devcanon projects found yet.";elements.projects.replaceChildren(empty);return}elements.projects.replaceChildren(...projects.map(path=>{const button=document.createElement("button");button.className=`project-item${path===project?" active":""}`;button.title=path;const glyph=document.createElement("span");glyph.className="project-glyph";glyph.textContent="◇";const label=document.createElement("span");label.textContent=basename(path);button.append(glyph,label);button.addEventListener("click",()=>loadProject(path));return button}))}
function clearProjectSearch(){projectQuery="";elements.projectSearch.value="";renderProjects();elements.projectSearch.focus()}
async function discoverProjects(){elements.refreshProjects.disabled=true;elements.refreshProjects.classList.add("scanning");elements.projectScanStatus.textContent="Scanning…";try{discoveredProjects=await invoke("discover_projects");elements.projectScanStatus.textContent=discoveredProjects.length?"Detected":"None found";renderProjects()}catch(error){elements.projectScanStatus.textContent="Scan unavailable";notify(String(error),true)}finally{elements.refreshProjects.disabled=false;elements.refreshProjects.classList.remove("scanning")}}
function openLauncher(){elements.projectModal.hidden=false;elements.newProject.focus()}
function closeLauncher(){elements.projectModal.hidden=true}
function notesList(notes){const lines=(notes||"A faster, safer Devcanon Studio experience.").split("\n").map(line=>line.replace(/^[-*#\s]+/,"").trim()).filter(Boolean).slice(0,6);const list=document.createElement("ul");list.replaceChildren(...lines.map(line=>{const item=document.createElement("li");item.textContent=line;return item}));return list}
async function loadProject(path){if(dirty){notify("Save your current changes before switching projects.",true);return}try{const files=await invoke("list_standards",{project:path});project=path;current="";elements.name.textContent=basename(project);elements.count.textContent=String(files.length);elements.files.replaceChildren(...files.map(relative=>{const button=document.createElement("button");button.className="file-item";button.textContent=relative;button.title=relative;button.addEventListener("click",()=>openFile(relative,button));return button}));elements.standardsUpdate.disabled=false;elements.openInEditor.disabled=false;elements.save.disabled=true;elements.editor.hidden=true;elements.empty.hidden=false;elements.empty.querySelector("h2").textContent=files.length?"Choose a standard from the sidebar.":"No standards found.";elements.empty.querySelector("p:not(.eyebrow)").textContent=`${files.length} standards detected in ${basename(project)}.`;rememberProject(project);setDirty(false);notify(`Opened ${basename(project)}`)}catch(error){notify(String(error),true)}}
async function chooseExisting(){closeLauncher();try{const selected=await invoke("choose_project");if(selected)await loadProject(selected)}catch(error){notify(String(error),true)}}
async function createProject(){closeLauncher();notify("Choose an empty or existing project folder to initialize.");try{const selected=await invoke("initialize_project");if(selected)await loadProject(selected)}catch(error){notify(String(error),true)}}
async function openFile(relative,button){if(dirty){notify("Save your current changes before opening another standard.",true);return}try{current=relative;elements.editor.value=await invoke("read_standard",{project,relative});elements.name.textContent=relative;elements.empty.hidden=true;elements.editor.hidden=false;elements.save.disabled=false;document.querySelectorAll(".file-item").forEach(item=>item.classList.toggle("active",item===button));setDirty(false)}catch(error){notify(String(error),true)}}
async function save(){if(!current)return;try{await invoke("write_standard",{project,relative:current,contents:elements.editor.value});setDirty(false);notify(`${current} saved`)}catch(error){notify(String(error),true)}}
async function updateHandbook(){if(!project)return;try{elements.standardsUpdate.disabled=true;elements.standardsUpdate.textContent="Updating…";const result=await invoke("update_standards",{project});notify(result||"Handbook is up to date");await loadProject(project)}catch(error){notify(String(error),true)}finally{elements.standardsUpdate.disabled=false;elements.standardsUpdate.textContent="Update handbook"}}
function setCollapsed(collapsed){document.body.classList.toggle("sidebar-collapsed",collapsed);localStorage.setItem("devcanon-sidebar-collapsed",String(collapsed))}
function prepareUpdate(info){pendingUpdate=info;elements.availableVersion.textContent=`Version ${info.version}`;elements.appUpdate.hidden=false;elements.updateStatus.textContent="A newer Studio release is ready";elements.updateVersion.textContent=info.version;elements.updateNotes.replaceChildren(notesList(info.notes));elements.assetName.textContent=`Devcanon Studio ${info.version} · signed package`}
async function checkForUpdates(){try{const info=await invoke("check_for_app_update");if(info)prepareUpdate(info)}catch{elements.updateStatus.textContent="Update check unavailable"}}
function openUpdatePage(){if(!pendingUpdate)return;elements.updatePage.hidden=false}
function formatBytes(bytes){if(!bytes)return"0 MB";return`${(bytes/1024/1024).toFixed(1)} MB`}
function etaLabel(seconds){if(!Number.isFinite(seconds)||seconds<=0)return"Calculating time remaining…";if(seconds<60)return`About ${Math.ceil(seconds)} seconds remaining`;return`About ${Math.ceil(seconds/60)} minutes remaining`}
async function installUpdate(){if(!pendingUpdate)return;elements.installUpdate.disabled=true;elements.closeUpdate.hidden=true;elements.updateMessage.textContent="Downloading and verifying the signed update…";localStorage.setItem(welcomeKey,JSON.stringify({version:pendingUpdate.version,notes:pendingUpdate.notes}));let downloaded=0,total=0,startedAt=performance.now();const channel=new Channel();channel.onmessage=message=>{if(message.event==="Started"){total=message.data.contentLength||0;startedAt=performance.now();elements.assetStatus.textContent="↓";elements.assetSize.textContent=total?`${formatBytes(total)} signed update package`:"Signed update package"}else if(message.event==="Progress"){downloaded+=message.data.chunkLength;const elapsed=(performance.now()-startedAt)/1000;const percent=total?Math.min(100,downloaded/total*100):0;const speed=elapsed>0?downloaded/elapsed:0;elements.progressPercent.textContent=total?`${Math.round(percent)}%`:"…";elements.progressBar.style.width=total?`${percent}%`:"18%";elements.progressEta.textContent=total&&speed?etaLabel((total-downloaded)/speed):"Downloading update assets…";elements.assetProgress.textContent=total?`${formatBytes(downloaded)} / ${formatBytes(total)}`:formatBytes(downloaded)}else if(message.event==="Finished"){elements.progressPercent.textContent="100%";elements.progressBar.style.width="100%";elements.progressEta.textContent="Download complete";elements.assetStatus.textContent="✓";elements.updateMessage.textContent="Installing the update. Studio will restart automatically…"}};try{await invoke("install_app_update",{onEvent:channel})}catch(error){localStorage.removeItem(welcomeKey);elements.installUpdate.disabled=false;elements.closeUpdate.hidden=false;elements.updateMessage.textContent="The update could not be installed.";notify(String(error),true)}}
function showWelcomeIfNeeded(){try{const update=JSON.parse(localStorage.getItem(welcomeKey)||"null");if(!update||update.version!==studioVersion)return;localStorage.removeItem(welcomeKey);elements.welcomeVersion.textContent=`v${update.version}`;const lines=(update.notes||"Your desktop standards workflow is now up to date.").split("\n").map(line=>line.replace(/^[-*#\s]+/,"").trim()).filter(Boolean).slice(0,5);elements.welcomeFeatures.replaceChildren(...lines.map(line=>{const row=document.createElement("div");row.className="welcome-feature";const icon=document.createElement("span");icon.textContent="✓";const text=document.createElement("p");text.textContent=line;row.append(icon,text);return row}));elements.welcomeModal.hidden=false}catch{localStorage.removeItem(welcomeKey)}}
async function start(){renderProjects();setCollapsed(localStorage.getItem("devcanon-sidebar-collapsed")==="true");loadEditors();discoverProjects();try{const info=await invoke("studio_info");studioVersion=info.version;elements.version.textContent=`v${studioVersion}`;showWelcomeIfNeeded()}catch{elements.version.textContent="Studio"}checkForUpdates()}
elements.choose.addEventListener("click",openLauncher);elements.emptyOpen.addEventListener("click",openLauncher);elements.refreshProjects.addEventListener("click",discoverProjects);elements.projectSearch.addEventListener("input",event=>{projectQuery=event.target.value;renderProjects()});elements.projectSearch.addEventListener("keydown",event=>{if(event.key==="Escape"&&projectQuery){event.stopPropagation();clearProjectSearch()}});elements.clearProjectSearch.addEventListener("click",clearProjectSearch);elements.newProject.addEventListener("click",createProject);elements.existingProject.addEventListener("click",chooseExisting);elements.projectModal.addEventListener("click",event=>{if(event.target===elements.projectModal||event.target.closest("[data-close-modal]"))closeLauncher()});elements.openInEditor.addEventListener("click",toggleEditorMenu);elements.editorMenu.addEventListener("keydown",moveEditorFocus);document.addEventListener("click",event=>{if(!event.target.closest(".editor-picker"))closeEditorMenu()});elements.save.addEventListener("click",save);elements.standardsUpdate.addEventListener("click",updateHandbook);elements.editor.addEventListener("input",()=>setDirty(true));elements.collapse.addEventListener("click",()=>setCollapsed(true));elements.expand.addEventListener("click",()=>setCollapsed(false));elements.appUpdate.addEventListener("click",openUpdatePage);elements.closeUpdate.addEventListener("click",()=>elements.updatePage.hidden=true);elements.installUpdate.addEventListener("click",installUpdate);elements.finishWelcome.addEventListener("click",()=>elements.welcomeModal.hidden=true);window.addEventListener("keydown",event=>{if(event.key==="Escape"){closeLauncher();if(!elements.editorMenu.hidden){closeEditorMenu();elements.openInEditor.focus()}if(!elements.closeUpdate.hidden)elements.updatePage.hidden=true}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="o"){event.preventDefault();openLauncher()}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="s"){event.preventDefault();save()}});window.addEventListener("beforeunload",event=>{if(dirty)event.preventDefault()});start();
