const invoke=window.__TAURI__.core.invoke;
const elements={choose:document.querySelector("#choose-project"),emptyOpen:document.querySelector("#empty-open"),path:document.querySelector("#project-path"),files:document.querySelector("#file-list"),count:document.querySelector("#file-count"),name:document.querySelector("#file-name"),empty:document.querySelector("#empty-state"),editor:document.querySelector("#editor"),save:document.querySelector("#save"),state:document.querySelector("#save-state"),update:document.querySelector("#update"),toast:document.querySelector("#toast")};
let project="",current="",dirty=false,toastTimer;
function notify(message,error=false){clearTimeout(toastTimer);elements.toast.textContent=message;elements.toast.className=`toast visible${error?" error":""}`;toastTimer=setTimeout(()=>elements.toast.className="toast",3200)}
function setDirty(value){dirty=value;elements.state.textContent=current?(value?"Unsaved changes":"All changes saved"):"No file open"}
async function openProject(){try{const selected=await invoke("choose_project");if(!selected)return;project=selected;elements.path.textContent=project;const files=await invoke("list_standards",{project});elements.count.textContent=String(files.length);elements.files.replaceChildren(...files.map(relative=>{const button=document.createElement("button");button.className="file-item";button.textContent=relative;button.title=relative;button.addEventListener("click",()=>openFile(relative,button));return button}));elements.update.disabled=false;elements.empty.querySelector("h2").textContent=files.length?"Choose a standard from the sidebar.":"No standards found.";notify(`Opened ${files.length} standards`)}catch(error){notify(String(error),true)}}
async function openFile(relative,button){if(dirty){notify("Save your current changes before opening another standard.",true);return}try{current=relative;elements.editor.value=await invoke("read_standard",{project,relative});elements.name.textContent=relative;elements.empty.hidden=true;elements.editor.hidden=false;elements.save.disabled=false;document.querySelectorAll(".file-item").forEach(item=>item.classList.toggle("active",item===button));setDirty(false)}catch(error){notify(String(error),true)}}
async function save(){if(!current)return;try{await invoke("write_standard",{project,relative:current,contents:elements.editor.value});setDirty(false);notify(`${current} saved`)}catch(error){notify(String(error),true)}}
async function update(){try{elements.update.disabled=true;elements.update.textContent="Updating…";const result=await invoke("update_standards",{project});notify(result||"Standards are up to date");await openProject()}catch(error){notify(String(error),true)}finally{elements.update.disabled=false;elements.update.innerHTML="<span>↻</span> Update standards"}}
elements.choose.addEventListener("click",openProject);elements.emptyOpen.addEventListener("click",openProject);elements.save.addEventListener("click",save);elements.update.addEventListener("click",update);elements.editor.addEventListener("input",()=>setDirty(true));window.addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="o"){event.preventDefault();openProject()}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="s"){event.preventDefault();save()}});window.addEventListener("beforeunload",event=>{if(dirty)event.preventDefault()});
